import SwiftUI

// Generated by Supernova - do not modify manually
public extension Text {

    func textStyleTitle1() -> some View {
        return self
            .font(Font.custom("Inter-Bold", size: 48))
    }

    func textStyleTitle2() -> some View {
        return self
            .font(Font.custom("Inter-Bold", size: 32))
    }

    func textStyleTitle3() -> some View {
        return self
            .font(Font.custom("Inter-Bold", size: 24))
    }

    // large

    // regular

    func textStyleLargeregularNormal() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 18))
    }

    func textStyleLargeregularTight() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 18))
    }

    func textStyleLargeregularNone() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 18))
    }

    // medium

    func textStyleLargemediumNormal() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 18))
    }

    func textStyleLargemediumTight() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 18))
    }

    func textStyleLargemediumNone() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 18))
    }

    // semibold

    func textStyleLargesemiboldNormal() -> some View {
        return self
            .font(Font.custom("Inter-SemiBold", size: 18))
    }

    func textStyleLargesemiboldTight() -> some View {
        return self
            .font(Font.custom("Inter-SemiBold", size: 18))
    }

    func textStyleLargesemiboldNone() -> some View {
        return self
            .font(Font.custom("Inter-SemiBold", size: 18))
    }

    // regular

    // regular

    func textStyleRegularregularNormal() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 16))
    }

    func textStyleRegularregularTight() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 16))
    }

    func textStyleRegularregularNone() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 16))
    }

    // medium

    func textStyleRegularmediumNormal() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 16))
    }

    func textStyleRegularmediumNone() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 16))
    }

    // semibold

    func textStyleRegularsemiboldNormal() -> some View {
        return self
            .font(Font.custom("Inter-SemiBold", size: 16))
    }

    func textStyleRegularsemiboldNone() -> some View {
        return self
            .font(Font.custom("Inter-SemiBold", size: 16))
    }

    // small

    // regular

    func textStyleSmallregularNormal() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 14))
    }

    func textStyleSmallregularTight() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 14))
    }

    func textStyleSmallregularNone() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 14))
    }

    // medium

    func textStyleSmallmediumNormal() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 14))
    }

    func textStyleSmallmediumTight() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 14))
    }

    func textStyleSmallmediumNone() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 14))
    }

    // semibold

    func textStyleSmallsemiboldNormal() -> some View {
        return self
            .font(Font.custom("Inter-SemiBold", size: 14))
    }

    func textStyleSmallsemiboldTight() -> some View {
        return self
            .font(Font.custom("Inter-SemiBold", size: 14))
    }

    func textStyleSmallsemiboldNone() -> some View {
        return self
            .font(Font.custom("Inter-SemiBold", size: 14))
    }

    // tiny

    // regular

    func textStyleTinyregularNormal() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 12))
    }

    func textStyleTinyregularTight() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 12))
    }

    func textStyleTinyregularNone() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 12))
    }

    // medium

    func textStyleTinymediumNormal() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 12))
    }

    func textStyleTinymediumTight() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 12))
    }

    func textStyleTinymediumNone() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 12))
    }

    // semibold

    func textStyleTinysemiboldNormal() -> some View {
        return self
            .font(Font.custom("Inter-SemiBold", size: 12))
    }

    func textStyleTinysemiboldTight() -> some View {
        return self
            .font(Font.custom("Inter-SemiBold", size: 12))
    }

    func textStyleTinysemiboldNone() -> some View {
        return self
            .font(Font.custom("Inter-SemiBold", size: 12))
    }
}
