import SwiftUI

// Generated by Supernova - do not modify manually
public extension View {

    func shadowSmall() -> some View {
        return self.shadow(color: Color(.sRGB, red: 48/255, green: 49/255, blue: 51/255, opacity: 0.08), radius: 1, x: 0, y: 0) 
    }

    func shadowSmall2() -> some View {
        return self.shadow(color: Color(.sRGB, red: 48/255, green: 49/255, blue: 51/255, opacity: 0.08), radius: 8, x: 0, y: 0) 
    }

    func shadowMedium() -> some View {
        return self.shadow(color: Color(.sRGB, red: 48/255, green: 49/255, blue: 51/255, opacity: 0.08), radius: 2, x: 0, y: 0) 
    }

    func shadowMedium2() -> some View {
        return self.shadow(color: Color(.sRGB, red: 48/255, green: 49/255, blue: 51/255, opacity: 0.08), radius: 8, x: 0, y: 1) 
    }

    func shadowLarge() -> some View {
        return self.shadow(color: Color(.sRGB, red: 48/255, green: 49/255, blue: 51/255, opacity: 0.08), radius: 1, x: 0, y: 0) 
    }

    func shadowLarge2() -> some View {
        return self.shadow(color: Color(.sRGB, red: 48/255, green: 49/255, blue: 51/255, opacity: 0.1), radius: 24, x: 0, y: 1) 
    }
}